### ISSUE TITLE
[Research] Investigate options for E2E/visual/user-perspective testing

### ISSUE THREAD

**Issue by jkaltoft** [kirbydesign/designsystem#2210] opened 2022-05-03 07:35 UTC
https://www.cypress.io/ could be an obvious place to start

**Comment by MadsBuchmann** [comment] 2022-05-09 11:57
Conclusion could be used for solving: https://github.com/kirbydesign/designsystem/issues/2168

**Comment by MadsBuchmann** [comment] 2022-05-09 12:01
Duplicate of #2168

**Closed by MadsBuchmann** 2022-05-09 12:01 UTC
