### ISSUE TITLE
[BUG] Kirby-list cannot have a Header and section headers (on iOS)

### ISSUE THREAD

**Issue by askarby** [kirbydesign/designsystem#151] opened 2019-03-14 09:47 UTC
**Describe the bug**
iOS cannot render a kirby-list having **both** a header as well as section headers.

It's related to the following issues:
- https://github.com/telerik/nativescript-ui-feedback/issues/950
- https://github.com/telerik/nativescript-ui-feedback/issues/951

**To Reproduce**
1. Create a list with a header and a section headers
2. Open on iOS device / emulator

**Kirby version**
 - [e.g. 0.0.84]

**Expected behavior**
The list is able to render list with header and section headers

**Native (please complete the following information):**
 - Device: iPhone (any)
 - OS: iOS
 - Browser: n/a
 - Version: n/a

**Additional context**
Part of "Progress"'s [Nativescript UI](https://www.nativescript.org/ui-for-nativescript), hence not Open Source, and not possible to fix by ourselves.

**Comment by tbozhikov** [comment] 2019-05-09 16:03
Hi @askarby,

> Part of "Progress"'s Nativescript UI, hence not Open Source, and not possible to fix by ourselves.

Indeed, the Nativescript UI plugins are free but not open-source. However, contributions are possible for some time now after signing a mutual NDA. If you or anyone else is interested to contribute, contact us at nativescriptplugins@progress.com.

**Comment by jonasjensen-brolstark** [comment] 2019-05-31 09:03
It is fixed for android in version `6.3.0` og RadListView. But it still has issues for iOS, see [https://github.com/NativeScript/nativescript-ui-feedback/issues/1145](https://github.com/NativeScript/nativescript-ui-feedback/issues/1145)

**Comment by labanos** [comment] 2019-07-12 09:30
Duplicate of #422

**Closed by labanos** 2019-07-12 09:30 UTC
Labels: bug, component:List
