### ISSUE TITLE
[BUG] Hover effect on list with sections does not show hover effect on entire item

### ISSUE THREAD

**Issue by SanderJespersen** [kirbydesign/designsystem#407] opened 2019-07-03 13:10 UTC
**Describe the bug**
When hovering over an item in the list, the bottom part of item is not covered by the hover effect as shown on screenshot where hover is forced on two rows:
![image](https://user-images.githubusercontent.com/45875825/60592018-01adb400-9da0-11e9-8f2a-1251ce971e73.png)

Another screenshot where hover is forced on the top item and inspect is enabled while mouse is hovering over the lower item:
![image](https://user-images.githubusercontent.com/45875825/60592647-59005400-9da1-11e9-8c98-b73f670115b5.png)

The same issue occurs in the cookbook:
![image](https://user-images.githubusercontent.com/45875825/60592395-d8d9ee80-9da0-11e9-851e-f8af459a820c.png)

**To Reproduce**
1. Go to https://cookbook.kirby.design/home/showcase/list
2. Scroll down to list with sections 
3. Open developer console
4. Enabled inspect
5. Inspect a row and force hover
6. Repeat for row above or below
7. See whitespace

**Kirby version**
0.0.200

**Expected behavior**
That the hover effect covers the entire item.

**Screenshots**
Applied with relevant information in the description.

**Desktop (please complete the following information):**
 - OS: Windows 7 / macOS 10.14.5
 - Chrome
 - Version 75.0.3770.80 / 75.0.3770.100

**Native (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by jakobe** [comment] 2019-07-04 05:36
This is because the extra white space covers the shadow of the item above that would otherwise show through between each item. To really see this in effect you would have to force the hover on 2 items at once as you've done in the screenshots which isn't a real world scenario. Closing this.

**Comment by jakobe** [comment] 2019-07-04 08:07
The issue is more visible when row heights are low, as the additional whitespace makes the content look off-center:
![image](https://user-images.githubusercontent.com/9556693/60649997-843b7f80-9e43-11e9-9e13-63af8df2329a.png)

**Closed** 2019-07-11 12:49 UTC
Labels: bug, component:List
