### ISSUE TITLE
[BUG] - Alert wont close

### ISSUE THREAD

**Issue by MonsterGameDev** [kirbydesign/designsystem#909] opened 2020-02-05 13:21 UTC
**Describe the bug**
Under certain conditions dialog will not close.

**To Reproduce**
Difficult to reproduce - but the problem exists in  branch: 
feature/fix40-tilslutningsaftale-alert, when a user tries to access an account without tilslutningsaftale, app opens a "you cannot do this..." alert - which, as u might have guessed, cannot be closed.
Turns out that the object ionic is trying to close differs on the faulty modal from the ones who works.
The function opening the alert is an excact copy of how its done everywhere else
We might ofc try to dig out way down to the actual problem, but on the other hand, the function - hideTopmost() - is written with NativeScript in mind, and is as such - legacy.

And... the fact that ionic actually does have a native function "dismiss()" which solves the problem, leads me to think that it might be a better solution.

So - i would like to change:
public hideTopmost(data?: any): void {
    const modal = this.modals[this.modals.length - 1];
    if (!modal) {
      throw new Error(this.noModalRegisteredErrorMessage);
    }
    modal.close(data);
  }

to:

  public hideTopmost(data?: any): void {
    this.ionicModalController.dismiss();
  }

**Kirby version**

0.8.87

**Expected behavior**
I want all dialogs to be able to close

- OS: Mac
- Browser Chrome
- Version 79.0.3945.117

**Additional context**
Jakob knows about this problem ::-)

**Comment by mvindahl** [comment] 2020-02-08 23:04
I think that this is a duplicate of https://github.com/kirbydesign/designsystem/issues/895 as both issues seem to be related to the hideTopmost() function.

**Comment by MonsterGameDev** [comment] 2020-02-11 09:31
Yes that might very well be the case.
Anyways... WHEN someone takes this i hope the native ionic dissmiss method will be considered.
gimme a call if we should talk?

**Comment by jakobe** [comment] 2021-04-08 10:46
Fixed by #993

**Closed by jakobe** 2021-04-08 10:46 UTC
Labels: bug, component:Alert
