### ISSUE TITLE
[BUG] Close modal is periodically not working

### ISSUE THREAD

**Issue by laljyskebank** [kirbydesign/designsystem#596] opened 2019-09-10 11:00 UTC
**Describe the bug**
I Recurring-Payments we are using a Modal to show how a missing Direct Debit Agreement. If we are opening the dialog, sometimes the close function won't close the modal.

**To Reproduce**
1. Go to 'Faste Betalinger'
2. Click on 'FAB button'
3. Click on 'Opret betalingsservice aftale'
4. Click on 'Betales fra'
5. Pick an account with no Direct Debit Agreement
6. The Direct Debit Agreement modal is shown 
7. Click on 'Luk'
8. Repeat step 4 to 7 until the error occurs

**Kirby version**
 - [0.7.1]

**Expected behavior**
The modal schould close.

**Desktop (please complete the following information):**
OS: [Windows 7, OSX 10.14.6]
Browser [chrome 76.0.3809.132, safari 12.1.2 (14607.3.9)]

**Comment by labanos** [comment] 2019-09-11 06:23
@laljyskebank iOS8.1?? browser? does it also fail in app? or only browser?
Is there an error in the console in the browser when this happens?

**Comment by labanos** [comment] 2019-09-11 06:26
@laljyskebank btw - when the business requirements are so specific - it would be helpful with a user in s or mock, that has an account which meets the requirements (and point the account out too - so no guessing is required ;) - otherwise it is impossible for anyone else to reproduce this.

**Comment by laljyskebank** [comment] 2019-09-11 06:45
There is no error in the console. 
I have testet on an IOS emulator and here, i can't reproduce the error. Android is not working on my Mac, so this is not tested yet.
There is a mock user called "Faste betaling bruger uden tilslutningsaftale" and any account can be used to reproduce the error.

**Comment by labanos** [comment] 2019-09-11 08:05
@laljyskebank ok i am confused - if you cannot reproduce - where is the error happening then? 

Maybe update this section with specific data? (and remember to delete "false" data?

Desktop (please complete the following information):

OS: [Windows, OSX]
Browser [chrome, safari]
Version []
Native (please complete the following information):

Device: [e.g. iPhone6]
OS: [e.g. iOS8.1]
Browser [e.g. stock browser, safari]
Version [e.g. 22]

**Comment by labanos** [comment] 2019-09-11 08:09
@laljyskebank btw - cant see the user on mock master. Is it only on a branch?

**Comment by laljyskebank** [comment] 2019-09-11 10:58
I have updated Desktop information.
The bug is only reproduced on web and should be on master now.

**Comment by labanos** [comment] 2019-09-11 11:49
@laljyskebank catch 22 ;) if its web - i dont have a mock build yet (only app has mock..Anders is working on it).. so.. cannot reproduce.. if you can reproduce on web - on a desktop - are you 100% sure there is absolutely nothing in the console? (something could break "events" prior to clicking close - so the close itself might be silent?)

PS the modals i try elsewhere - eg. write message, transfer money.. which also has modal in modal.. doesnt have this issue as far as i can see. So are you sure it's a Kirby modal issue? Feels more like its a contextual issue - something else in DRB "breaks" things?

**Comment by laljyskebank** [comment] 2019-09-11 12:09
Alexander has been on the case and has detected it is a Kirby issue.

**Comment by labanos** [comment] 2019-09-11 13:19
@laljyskebank great =) @hafstad would you update the issue with your findings? unless ofc you already fixed it ;)

**Closed** 2019-09-24 10:31 UTC
Labels: bug, component:Modal
