### ISSUE TITLE
[Enhancement] Image Flavors (Card & Modal)

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#956] opened 2020-03-16 14:02 UTC
**Is your enhancement request related to a problem? Please describe.**
Our cards and modals can right now only be shown in a simple form.

Even though some teams use Images in Cards, there is no "one way to do it". So when looking at performance, loading etc. of the images there is no technical standard.

**Describe the solution you'd like**
We would like to be able to place Images inside some of our components like Cards and Modals.

**Cards:** Should fill the whole card - See also 

![Skærmbillede 2020-03-16 kl  14 51 22](https://user-images.githubusercontent.com/49033002/76764729-a0930880-6795-11ea-8149-aba7a947ce83.png)

**Modals:** Should fille the top of a modal and the content should scroll away like it would be a drawer that scrolls up.

![Skærmbillede 2020-03-16 kl  14 51 17](https://user-images.githubusercontent.com/49033002/76764737-a4268f80-6795-11ea-8924-03849a3a6c66.png)

**Describe alternatives you've considered**
In a modal it is basically the hero picture as also described here https://material.io/design/communication/imagery.html#hero-images

**Additional context**
We should handling loading our images consistently, like blurring the image or something instead of showing nothing until the image has been loaded. 

Look also at Wolt how they load their pictures, they are blurred in a low quality version until they have the picture. 

![IMG_5581](https://user-images.githubusercontent.com/49033002/76765709-219ecf80-6797-11ea-85c7-826bdc7a9576.PNG)

**Comment by jakobe** [comment] 2021-03-25 15:21
@bommariusser Isn't the 2nd part of this issue a duplicate of #1300 ? 🤔

**Comment by MadsBuchmann** [comment] 2022-02-03 13:49
I' beginning work on the _card_ part of this issue in: https://github.com/kirbydesign/designsystem/issues/2022 :D

**Comment by RasmusKjeldgaard** [comment] 2024-12-20 09:13
We are closing this issue as we are unsure about the requirements. Please re-open if the functionality is still needed.

**Closed by RasmusKjeldgaard** 2024-12-20 09:13 UTC
Labels: enhancement, component:Card, workaround possible, NOT Tech refined, NOT Prioritized, Tablet, needs more refinement
