### ISSUE TITLE
[BUG] Textarea not clickable in Kirby v6 on iOS and Android

### ISSUE THREAD

**Issue by MikaelKristoffersenBankdata** [kirbydesign/designsystem#2320] opened 2022-06-10 05:34 UTC
- [ ] I have written a [good issue](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Issue) 

## Describe the bug
Man kan ikke aktivere feltet til at skrive en kommentar på posteringsdetaljen.

## Describe how to reproduce the bug
1) Gå til posteirngslisten
2) Åbn en posteringsdetalje
3) Klik i kommentarfeltet
4) Se at man ikke kan aktivere feltet og skrive en kommentar

OBS! Er et problem på både android og iOS

## Which Kirby version was used?
Kirby 6 branch 

## What was the expected behavior?
Se den kørende master branch for expected behavior

## Checklist:

The following tasks should be carried out in sequence in order to follow [the process of contributing](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#the-process-of-contributing) correctly.

### Verification
To make sure the bug is not intended behaviour; it should be verified by a member of team Kirby before moving on to implementation. 

- [ ] Make sure the `NOT verified` label has been removed by a member of [team Kirby](https://github.com/kirbydesign/designsystem/blob/main/.github/SUPPORT.md#team-kirby); do not proceed until this is done

### Implementation 
The contributor who wants to implement this issue should: 

- [ ] Make sure you have read: "[Before you get coding](https://github.com/kirbydesign/designsystem/blob/main/.github/CONTRIBUTING.md/#before-you-get-coding)".
- [ ] Signal to others you are working on the issue by assigning yourself.
- [ ] Create a branch from the [develop branch](https://github.com/kirbydesign/designsystem/tree/develop) following our [branch naming convention](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Branch). 
- [ ] Create a test that reproduces the bug following guidelines in: "[The good: Test](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Test)". 
- [ ] Write code to fix the bug

### Review
Once the issue has been implemented and is ready for review:

- [ ] Do a [self-review](https://github.com/kirbydesign/designsystem/wiki/The-Good%3A-Self-review). 
- [ ] Create a pull-request.

**Comment by mictro** [comment] 2022-11-11 10:54
Talked to Mikkel Kristoffersen,
The issue was caused by an unfortunate placement of buttons inside a text-area.
The problem has been resolved by using a better and more healthy component layout.

Mikkel asked Kirby to close the issue since the issue since is not related to defect kirby-component.

**Closed by mictro** 2022-11-11 10:54 UTC
Labels: bug, good first issue, NOT Prioritized, NOT Verified
