### ISSUE TITLE
[Enhancement] Tabbar height - desktop and tablet

### ISSUE THREAD

**Issue by henrikvoetmand** [kirbydesign/designsystem#1249] opened 2021-01-20 13:29 UTC
**Is your enhancement request related to a problem? Please describe.**
The current height of the tabbar on desktop does not fit the different design of PI logo's. The height/width ratio of the logo's vary a lot. 

**Describe the solution you'd like**
Extend the tabbar height on tablet and desktop to 70px. As designed.

**Tablet**
<img width="839" alt="Skærmbillede 2021-01-20 kl  14 16 04" src="https://user-images.githubusercontent.com/71710012/105180768-41c3bb80-5b2b-11eb-9f0d-d0393c9e2f96.png">

**Desktop**
<img width="1090" alt="Skærmbillede 2021-01-20 kl  14 16 27" src="https://user-images.githubusercontent.com/71710012/105180854-60c24d80-5b2b-11eb-8e1a-a7802931aa54.png">

**Zeplin**
https://zpl.io/a7XoKLp

**Describe alternatives you've considered**
A clear and concise description of any alternative solutions or enhancement you've considered.

**Additional context**

**Comment by jkaltoft** [comment] 2021-02-03 12:04
@jakobe, my thoughts:

- Extend [tabs.component.spec.ts](https://github.com/kirbydesign/designsystem/blob/1c18b59505f2db2f9fa407839c2f4bb971b87412/libs/designsystem/src/lib/components/tabs/tabs.component.spec.ts#L93)
  - Test screensize tablet and desktop to check that height is 70px
  - Test screensize phone to check that height *is not* 70px - or test that height *is* 50px (the current height)
-  Use `--kirby-tab-bar-height` as height for `ion-tab-bar` in [tabs.component.scss](https://github.com/kirbydesign/designsystem/blob/1c18b59505f2db2f9fa407839c2f4bb971b87412/libs/designsystem/src/lib/components/tabs/tabs.component.scss#L15)
    - This may not be strictly required. Apparently `--kirby-tab-bar-height` is not being used - I assume `ion-tab-bar` gets it's height from ionic...?
- Create new global styles custom property `--kirby-tab-bar-height-medium-up` or `--kirby-tab-bar-height-tall` (or something... name suggestions are welcome 😄 ) with a value of the desired 70px.
- Use new custom property as height for `ion-tab-bar` with a "tablet and above" breakpoint.
    - Would that breakpoint be `>=small`?

**Comment by jkaltoft** [comment] 2021-02-03 12:21
@henrikvoetmand In Zeplin it looks like the tab bar on mobile should be 48px, and not 50px (51px including a border) like it currently is in the cookbook. Should I change it for mobile too, or is it out of scope for this issue?

**Zeplin:**

![image](https://user-images.githubusercontent.com/150451/106746009-33dd6280-6622-11eb-9187-56003fc7335a.png)

**Cookbook:**

![image](https://user-images.githubusercontent.com/150451/106746194-7acb5800-6622-11eb-88d2-bf43f2b075f9.png)

![image](https://user-images.githubusercontent.com/150451/106746339-af3f1400-6622-11eb-9857-2c7e08d07f28.png)

**Comment by jakobe** [comment] 2021-02-03 12:30
@jkaltoft Good thinking 👍 
Yes apparently, ion-tab-bar has a hardcoded height of 50px: https://github.com/ionic-team/ionic-framework/blob/master/core/src/components/tab-bar/tab-bar.ios.scss#L15
And yes, we currently don't use that variable inside Kirby-tabs, but it's being used as a helper variable when using tabs as part of an desktop app header (to set the height of the logo-wrapper in this example):
![image](https://user-images.githubusercontent.com/9556693/106746957-8c612f80-6623-11eb-9cb0-1aa863267ef9.png)

So 👉 : I would reuse that existing variable, and set the height of the ion-tab-bar as suggested. Then using the same media that flips the tabs/content and places the tabs at the top, I would set the variable to 70px:
https://github.com/kirbydesign/designsystem/blob/master/libs/designsystem/src/lib/components/tabs/tabs.component.scss

**Comment by jakobe** [comment] 2021-02-03 12:43
> @henrikvoetmand In Zeplin it looks like the tab bar on mobile should be 48px, and not 50px (51px including a border) like it currently is in the cookbook. Should I change it for mobile too, or is it out of scope for this issue?
> 
> **Zeplin:**
> 
> ![image](https://user-images.githubusercontent.com/150451/106746009-33dd6280-6622-11eb-9187-56003fc7335a.png)
> 
> **Cookbook:**
> 
> ![image](https://user-images.githubusercontent.com/150451/106746194-7acb5800-6622-11eb-88d2-bf43f2b075f9.png)
> 
> ![image](https://user-images.githubusercontent.com/150451/106746339-af3f1400-6622-11eb-9857-2c7e08d07f28.png)

@jkaltoft That ☝️  might involve a bigger regression test on devices than the other change which only involves web/desktop that's isn't in production yet (and yes, 2px is not a biggie, but it could have an impact somewhere that we don't know about)

**Comment by henrikvoetmand** [comment] 2021-02-03 12:46
@jkaltoft @jakobe I agree with Jakob - let's leave the mobile height out of scope for this.

**Closed** 2021-02-05 05:01 UTC
Labels: NOT Prioritized, component:Tabs, enhancement, good first issue
