### ISSUE TITLE
[BUG] badge in avartar has wrong size, when used in a kirby-list

### ISSUE THREAD

**Issue by jvh2** [kirbydesign/designsystem#537] opened 2019-08-20 13:29 UTC
When using the kirby badge in an avatar that is placed in a kirby-listm the badge has wrong size. In kirby design system the badge in avatar is 16x16. When using badge in avatar the actual size is 26x26

<kirby-avatar size="lg" overlay="true" [imageSrc]="imageSrc" shadow="true"> 
      <kirby-badge themeColor="danger">1</kirby-badge>
</kirby-avatar>

**To Reproduce**
1. add badge to avatar in https://cookbook.kirby.design/home/showcase/list (List with custom content:)

**Kirby version**
 - 0.0.242

**Expected behavior**
badge is 16x16 when used in avatar. 
<img width="513" alt="Screenshot 2019-08-20 at 15 21 16" src="https://user-images.githubusercontent.com/42968668/63350735-43011f80-c35e-11e9-8ea0-655639dca67a.png">

**Comment by labanos** [comment] 2019-08-21 11:33
@bommariusser - sounds like a duplicate of #498 rather than a bug - do you agree?

@jvh2 you tagged this web? as i see it this is also native? (the web and native labels were means for issue "only" on either platform)

**Comment by bommariusser** [comment] 2019-08-21 12:45
@labanos @jvh2 Hmm thats weird :) 

https://github.com/kirbydesign/designsystem/issues/498 is about making a smaller version of the badge eg. 8x8. 

The original version of the badge is 16x16 so it looks like this version is 26x27? 

It looks fine in cookbook, have you tried with another icon? @jvh2

**Comment by jvh2** [comment] 2019-08-21 13:14
@bommariusser yes the size i get i 26x27. 

In the cookbook it looks fine yes :-) but when you add the bagde in a kirby list:

https://cookbook.kirby.design/home/showcase/list

then the size is wrong. Lets talk tommorror :-)

**Comment by bommariusser** [comment] 2019-08-21 14:48
@jvh2 sygt fjollet at badge virker på avatar, men når man så putter det ind i en liste at det breaker? ;) Der mangler lige en showcase på list der viser denne usecase :) 

men nu skriver du: <kirby-avatar size="lg" overlay="true" [imageSrc]="imageSrc" shadow="true"> som er en avatar uden badge, men det er vel: (antager det er også noget ala det du har lavet)

 <kirby-avatar size="lg" overlay="true" [imageSrc]="imageSrc" shadow="true"> 
     <kirby-badge themeColor="danger">
                <kirby-icon name="????"></kirby-icon>
     </kirby-badge>
</kirby-avatar>

**Closed** 2019-08-22 09:57 UTC
Labels: Web, bug, component:Avatar
