### ISSUE TITLE
[Enhancement] Modal title should be changable

### ISSUE THREAD

**Issue by MonsterGameDev** [kirbydesign/designsystem#747] opened 2019-11-04 10:06 UTC
**Is your enhancement request related to a problem? Please describe.**
After more and more navigation gets to happen within the same modal, the need to change the title as user navigates becomes an issue - that is if we have to follow the UX guidelines

**Describe the solution you'd like**
I want to be able to change the modal title from the component, the route or whatever makes sense

**Describe alternatives you've considered**
The title is set through a servce - i beleive (without having investigated throughly) that a public method changeTitle(newTitle: string) should be implemented

**Additional context**
Be nice to little animals ....

**Comment by labanos** [comment] 2019-11-04 12:38
Duplicate of #677

**Closed by labanos** 2019-11-04 12:38 UTC
Labels: enhancement
