### ISSUE TITLE
[BUG] Empty-State icon is not shown correct in Edge browser

### ISSUE THREAD

**Issue by laljyskebank** [kirbydesign/designsystem#672] opened 2019-10-10 12:31 UTC
**Describe the bug**
The icon in Empty State is not shown correct in Edge browser. The icon is half size

**To Reproduce**
1. Go to https://cookbook.kirby.design/home/showcase/empty-state

**Kirby version**
 - 0.7.32

**Expected behavior**
See chrome for correct size of icon

**Screenshots**

- Edge browser
![image](https://user-images.githubusercontent.com/35138247/66568169-2799e000-eb69-11e9-92d4-1d504afd74ab.png)

- Chrome browser
<img width="1675" alt="Screen Shot 2019-10-10 at 14 28 27" src="https://user-images.githubusercontent.com/35138247/66568692-40ef5c00-eb6a-11e9-9b25-32f4badea971.png">

**Comment by jonasjensen-brolstark** [comment] 2020-01-23 12:57
Using the newest version of Edge (chromium based version) the empty state looks like this:

![image](https://user-images.githubusercontent.com/46445487/72986278-28891180-3de8-11ea-9950-3f79ca2f41ca.png)

@laljyskebank can you confirm and maybe close the issue?

**Comment by laljyskebank** [comment] 2020-02-03 12:36
The problem is still in Microsoft Edge
<img width="689" alt="Microsoft Edge Empty state" src="https://user-images.githubusercontent.com/35138247/73653713-1fbafa00-468a-11ea-872a-c3fa427348f8.png">

**Comment by bommariusser** [comment] 2021-03-03 07:06
@laljyskebank still an issue? i cant reproduce it

**Comment by jakobe** [comment] 2021-04-09 08:18
Fixed by Edge using Chromium now

**Closed by jakobe** 2021-04-09 08:18 UTC
Labels: bug, component:Empty State
