### ISSUE TITLE
[Enhancement] Native Spinner Looks

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#271] opened 2019-05-15 10:58 UTC
**Is your enhancement request related to a problem? Please describe.**
We want the Native Spinner to look like the Web spinner, so it should behave in the same way as the Web spinner.

See also zeplin as reference, even though the Web spinner is the right look we want to achieve:
https://zpl.io/aX30KOX

**Comment by hafstad** [comment] 2019-06-19 13:28
possible duplicate of #244

**Comment by labanos** [comment] 2019-07-12 11:07
Duplicate of #244 (part of fixing 244 will be fixing this)

**Closed by labanos** 2019-07-12 11:07 UTC
Labels: component:Spinner, effort: days, enhancement, low priority, research needed
