### ISSUE TITLE
[Enhancement] Scroll-up when pressing tab-item on very first page

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#723] opened 2019-10-27 09:07 UTC
**Is your enhancement request related to a problem? Please describe.**
When you are on the very first page of a tab-item, eg. konto & inbox and you have scrolled down, the view should scroll up when you press the tab-item again.

**Comment by labanos** [comment] 2019-12-09 12:04
Duplicate of #682

**Closed by labanos** 2019-12-09 12:04 UTC
Labels: BØR, component:Page, enhancement
