### ISSUE TITLE
Modals hide scroll on host page so content "jumps"

### ISSUE THREAD

**Issue by daviddyrholm** [kirbydesign/designsystem#1197] opened 2020-11-13 10:17 UTC
**Describe the bug**
When opening a model on a page which has scroll (is higher than the screen) the scrollbar is hidden while the modal is visible. When the modal is closed the scrollbar is revealed again, pushing the main page content to the left, which to the user looks like content "jumps" to the left.

**To Reproduce**

1. Go to https://cookbook.kirby.design/home/showcase/modal in Chrome or Firefox
2. Notice the scrollbar on the right side of the page
3. Click the "Show modal"-button located under Desktop -> With component (default)
4. Notice the scrollbar is now missing on the right
5. Close the modal - notice that content on the main page "jump"s
6. Notice that the scrollbar on the right is now visible again. 

**Kirby version**
- v1.3.2

**Expected behavior**
Opening a modal should not affect content on the main page.

**Please complete the following information:**
- OS: Windows 7
- Browser Chrome 86.0.4240.183 (Officiel version) (64-bit), Firefox 82.0.1 (64-bit)

**Severity**
It is only a minor annoyance that sometimes make users question if something is wrong with the page. 

## Tasks:
- [ ] Move issue from "Ready to do" -> "in progress" on our [project board](https://github.com/kirbydesign/designsystem/projects/1)
- [ ] Create Fix Branch
- [ ] Create test reproducing the error
- [ ] Fix
- [ ] If relevant [Update Examples and Showcase](https://cookbook.kirby.design/home/showcase/button)
- [ ] Push commits to GitHub
- [ ] Open a pull request (remember to add `closes #issueno` to the description) and ask @kirbydesign/kirby-guild for review
- [ ] Merge to master and delete branch

**Comment by bommariusser** [comment] 2020-11-14 10:32
We talked about this several times in our team and categorized it to be related to underlying OS (Windows) @daviddyrholm so it'll be hard to fix even though we totally get that its not the intended behavior :) 

Also which device have you tested it on? :)

**Comment by bommariusser** [comment] 2020-12-04 16:10
@daviddyrholm ?

**Comment by jakobe** [comment] 2021-04-16 06:01
@daviddyrholm Closing this, as the no-scroll behaviour is by design. As @bommariusser mentions this is really an issue related to the underlying OS (i.e. works fine on Chrome for MacOS) and whether the modal is used in an app context or not (the kirby-app doesn't allow scrolling the body element in the first place).
If it's an annoyance in your particular use case you could consider applying padding to the `body` element with the same spacing as the scrollbar takes up in that particular browser/platform. You can use the `body.backdrop-no-scroll` selector that gets applied to the `body` element, when the modal is open.

**Closed by jakobe** 2021-04-16 06:01 UTC
Labels: NOT Prioritized, NOT Tech refined, Web, bug, component:Modal
