### ISSUE TITLE
[BUG] Kirby page is triggering onEnter event on swipe back

### ISSUE THREAD

**Issue by lydemann** [kirbydesign/designsystem#903] opened 2020-01-31 12:54 UTC
**Describe the bug**
Kirby page is triggering onEnter event on swipe back. 

**To Reproduce**

1. Go to page 1
2. Navigate to page 2 (that is subscribing to onEnter page event)
3. Swipe back to page 2
4. See onEnter is being called on the swipe back

**Kirby version**

- 0.8.87

**Expected behavior**
Swiping back should not trigger onEnter for the page you are swiping back from.

**Screenshots**

**Please complete the following information:**

- OS: Windows, MacOS, iOS
- Browser Chrome, Safari

**Comment by jakobe** [comment] 2021-04-08 10:49
Duplicate of #1259

**Closed by jakobe** 2021-04-08 10:49 UTC
Labels: bug, component:Page
