### ISSUE TITLE
[Enhancement] configure background colour for list

### ISSUE THREAD

**Issue by SilverGull** [kirbydesign/designsystem#154] opened 2019-03-14 13:41 UTC
Currently the standard background colour for lists and list headers is "--kirby-surface" (white) and transparent for section headers. We need to be able to configure it. Our current use cases require us to have "--kirby-background" (grey) for both body, header and section header (or transparent).

An overall list styling issue exist as well https://github.com/kirbydesign/designsystem/issues/146

**Comment by SilverGull** [comment] 2019-03-18 09:21
After consulting with Mads Norlyk, The current requirement for background colour in lists are:
- transparent header background (is already for section header)
- configureable background colour for body (including transparent as an option)

**Comment by SilverGull** [comment] 2019-03-21 08:21
**WEB**
To mimic Ionic we may want to create new --background css variables for each component in the list. The developer can then overwrite this variable instead of the kirby css variable.

_kirby-list.css_
```
:host {
  --background: var(--kirby-background);
  .body {
    background-color: var(--background);
  }
}
```

_my-drb-component.css_
```
some-kirby-component {
  --background: blue;
}
```

For this to work in in list-section-header, we may want to change the implementation to use content projection into the list-section-header. I couldn't get it to work by just changing how and where it is styled.

**NATIVE**
We cannot use css 4 variables, so we will have to overwrite the sass variables somehow. @jakobe and @Rolchau will look into it.

**Comment by labanos** [comment] 2019-07-12 10:51
Duplicate of #227

**Closed by labanos** 2019-07-12 10:51 UTC
Labels: component:List, duplicate, enhancement
