### ISSUE TITLE
[BUG] FAB fires more then once

### ISSUE THREAD

**Issue by bommariusser** [kirbydesign/designsystem#313] opened 2019-05-24 08:35 UTC
**Describe the bug**
When pressing the FAB more than once, very fast, it fires more than once.

**To Reproduce**
1. Go to 'indbakke'
2. Click on 'opret ny besked' twice very fast
3. See at least 2 modals on top of each other

**Expected behavior**
Disable button upon first press

**Comment by jakobe** [comment] 2019-06-06 13:00
Will be fixed by a `disableWhenSelected` property on kirby button used by FAB sheet (#229)

**Closed by jakobe** 2019-06-06 13:00 UTC
Labels: bug, component:FAB, effort: hours

**Comment by jakobe** [comment] 2019-09-19 18:00
Cannot reproduce
