### ISSUE TITLE
[BUG] Overflow of list items is not possible anymore (Web)

### ISSUE THREAD

**Issue by hafstad** [kirbydesign/designsystem#509] opened 2019-08-10 12:26 UTC
**Describe the bug**
Overflow of list-items with negative margin or negative positioning is not possible anymore, after changing to the ionic implementation. **THIS IS WEB ONLY**

**To Reproduce**
1. Use kirby list with an list item which has some element trying overflow
2. As seen on the screenshot you will see the overflowing element be hidden

**Screenshots**
![image](https://user-images.githubusercontent.com/5496706/62821797-c199d800-bb7a-11e9-8b10-cf51deb6c84a.png)

**Kirby version**
 - v0.0.251

**Expected behavior**
It should be possible to overflow the ion-item to be able to support different use-cases.

**Additional context**
The reason for this is that we don't assign transclued content inside of any slot's of ion-item therefore it defaults to input-wrapper which has overflow:hidden 

Solution is therefore assigning the content to the start slot, as this inherit the overflow of ion-item. However input-wrapper don't see: 
https://github.com/ionic-team/ionic/pull/18502

**Comment by mmmtrifork** [comment] 2019-08-14 06:59
I couldn't reproduce this

**Comment by jonasjensen-brolstark** [comment] 2019-09-27 09:02
Fixed in version `0.7.12`.

**Closed by jonasjensen-brolstark** 2019-09-27 09:02 UTC
Labels: Web, bug, component:List, effort: hours
