### ISSUE TITLE
[BUG] Scroll position after swipe back

### ISSUE THREAD

**Issue by jvh2** [kirbydesign/designsystem#727] opened 2019-10-28 09:10 UTC
After introducing page-template, swiping back from posting-list to account-list and swiping back from posting-details to postinglist, the scroll start at top.

**To Reproduce**
Find a user with many accounts (cpr 1507871867) and scroll to bottom, then select an account and swipe back from postinglist, the account list is now scrolled to top, instead of the selected item position

**Kirby version**
- 0.8.12

**Expected behavior**
Swiping back to a scroll list should remember the selected item position in the scroll list

Tested on ios 13.1.3 and newer android.

**Comment by labanos** [comment] 2019-10-30 21:32
@jvh2 hmm i cannot consistently reproduce this. Could it be related to when you update the postinglist? (not sure when or how often you do so on navigation?)

**Comment by labanos** [comment] 2019-11-04 07:53
Seems to be a general problem - a quick swipe can consistently reproduce the issue. While a slower one seems to "work as intended".

Using back on the toolbar works as intended.

**Comment by labanos** [comment] 2019-12-09 11:20
cannot reproduce anymore - has most likely been fixed by other fixes.

**Closed by labanos** 2019-12-09 11:20 UTC
Labels: BØR, bug, component:Page
