### ISSUE TITLE
[Enhancement] Callback when Modal has finished animation

### ISSUE THREAD

**Issue by ckibsen** [kirbydesign/designsystem#659] opened 2019-10-04 12:02 UTC
**Is your enhancement request related to a problem? Please describe.**
We wan't to automatically set focus in an input field, after the modal has been shown. However, if the modal hasn't finished animating when our code is run, our focus request is in vain. 

**Describe the solution you'd like**
We wish for a callback from the ModalController when it has finished animating, to ensure that we don't take action before our component is loaded and ready for input. 

**Describe alternatives you've considered**
A timeout with some magic number, before we try to set focus in the input field, but this isn't really a nice solution!

**Additional context**
I'd expect input field to have focus here!
![Simulator Screen Shot - iPhone 8 - 2019-10-04 at 14 01 19](https://user-images.githubusercontent.com/832287/66206137-7ea63d80-e6af-11e9-8a61-e2774d395ff8.png)

**Comment by labanos** [comment] 2019-10-29 16:23
Closing this as the request aims to fix a fundamental problem with focus on iOS - not related to modals. The issues is there on "til dig", as well as "equity search" and "create pincode/enter pincode".

T2 or T5 POs has already discussed who might look into this first - as it might require som digging around. (googling iOS input focus 

PS the issue is "worst" on transfer - where there is only 1 input - which is not really visible.. leaving the user "stuck" - the other places are "less" bad - but still annoying.

**Closed by labanos** 2019-10-29 16:23 UTC
Labels: component:Modal, enhancement, research needed
